// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

public interface AllocateDataNodesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.westboy.namenode.rpc.AllocateDataNodesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileInfo = 1;</code>
   * @return The fileInfo.
   */
  java.lang.String getFileInfo();
  /**
   * <code>string fileInfo = 1;</code>
   * @return The bytes for fileInfo.
   */
  com.google.protobuf.ByteString
      getFileInfoBytes();
}
