// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

/**
 * Protobuf type {@code com.westboy.namenode.rpc.ChooseDataNodeRequest}
 */
public final class ChooseDataNodeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.westboy.namenode.rpc.ChooseDataNodeRequest)
    ChooseDataNodeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChooseDataNodeRequest.newBuilder() to construct.
  private ChooseDataNodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChooseDataNodeRequest() {
    filename_ = "";
    excludedDatanodeInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChooseDataNodeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChooseDataNodeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            filename_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            excludedDatanodeInfo_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.westboy.namenode.rpc.model.NameNodeRpcModel.internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.westboy.namenode.rpc.model.NameNodeRpcModel.internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.westboy.namenode.rpc.model.ChooseDataNodeRequest.class, com.westboy.namenode.rpc.model.ChooseDataNodeRequest.Builder.class);
  }

  public static final int FILENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object filename_;
  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCLUDEDDATANODEINFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object excludedDatanodeInfo_;
  /**
   * <code>string excludedDatanodeInfo = 2;</code>
   * @return The excludedDatanodeInfo.
   */
  @java.lang.Override
  public java.lang.String getExcludedDatanodeInfo() {
    java.lang.Object ref = excludedDatanodeInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      excludedDatanodeInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string excludedDatanodeInfo = 2;</code>
   * @return The bytes for excludedDatanodeInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExcludedDatanodeInfoBytes() {
    java.lang.Object ref = excludedDatanodeInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      excludedDatanodeInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFilenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
    }
    if (!getExcludedDatanodeInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, excludedDatanodeInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFilenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
    }
    if (!getExcludedDatanodeInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, excludedDatanodeInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.westboy.namenode.rpc.model.ChooseDataNodeRequest)) {
      return super.equals(obj);
    }
    com.westboy.namenode.rpc.model.ChooseDataNodeRequest other = (com.westboy.namenode.rpc.model.ChooseDataNodeRequest) obj;

    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (!getExcludedDatanodeInfo()
        .equals(other.getExcludedDatanodeInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (37 * hash) + EXCLUDEDDATANODEINFO_FIELD_NUMBER;
    hash = (53 * hash) + getExcludedDatanodeInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.westboy.namenode.rpc.model.ChooseDataNodeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.westboy.namenode.rpc.ChooseDataNodeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.westboy.namenode.rpc.ChooseDataNodeRequest)
      com.westboy.namenode.rpc.model.ChooseDataNodeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.westboy.namenode.rpc.model.NameNodeRpcModel.internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.westboy.namenode.rpc.model.NameNodeRpcModel.internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.westboy.namenode.rpc.model.ChooseDataNodeRequest.class, com.westboy.namenode.rpc.model.ChooseDataNodeRequest.Builder.class);
    }

    // Construct using com.westboy.namenode.rpc.model.ChooseDataNodeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      filename_ = "";

      excludedDatanodeInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.westboy.namenode.rpc.model.NameNodeRpcModel.internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_descriptor;
    }

    @java.lang.Override
    public com.westboy.namenode.rpc.model.ChooseDataNodeRequest getDefaultInstanceForType() {
      return com.westboy.namenode.rpc.model.ChooseDataNodeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.westboy.namenode.rpc.model.ChooseDataNodeRequest build() {
      com.westboy.namenode.rpc.model.ChooseDataNodeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.westboy.namenode.rpc.model.ChooseDataNodeRequest buildPartial() {
      com.westboy.namenode.rpc.model.ChooseDataNodeRequest result = new com.westboy.namenode.rpc.model.ChooseDataNodeRequest(this);
      result.filename_ = filename_;
      result.excludedDatanodeInfo_ = excludedDatanodeInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.westboy.namenode.rpc.model.ChooseDataNodeRequest) {
        return mergeFrom((com.westboy.namenode.rpc.model.ChooseDataNodeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.westboy.namenode.rpc.model.ChooseDataNodeRequest other) {
      if (other == com.westboy.namenode.rpc.model.ChooseDataNodeRequest.getDefaultInstance()) return this;
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        onChanged();
      }
      if (!other.getExcludedDatanodeInfo().isEmpty()) {
        excludedDatanodeInfo_ = other.excludedDatanodeInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.westboy.namenode.rpc.model.ChooseDataNodeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.westboy.namenode.rpc.model.ChooseDataNodeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object filename_ = "";
    /**
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filename_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      
      filename_ = getDefaultInstance().getFilename();
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filename_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object excludedDatanodeInfo_ = "";
    /**
     * <code>string excludedDatanodeInfo = 2;</code>
     * @return The excludedDatanodeInfo.
     */
    public java.lang.String getExcludedDatanodeInfo() {
      java.lang.Object ref = excludedDatanodeInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excludedDatanodeInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string excludedDatanodeInfo = 2;</code>
     * @return The bytes for excludedDatanodeInfo.
     */
    public com.google.protobuf.ByteString
        getExcludedDatanodeInfoBytes() {
      java.lang.Object ref = excludedDatanodeInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        excludedDatanodeInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string excludedDatanodeInfo = 2;</code>
     * @param value The excludedDatanodeInfo to set.
     * @return This builder for chaining.
     */
    public Builder setExcludedDatanodeInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      excludedDatanodeInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string excludedDatanodeInfo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExcludedDatanodeInfo() {
      
      excludedDatanodeInfo_ = getDefaultInstance().getExcludedDatanodeInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string excludedDatanodeInfo = 2;</code>
     * @param value The bytes for excludedDatanodeInfo to set.
     * @return This builder for chaining.
     */
    public Builder setExcludedDatanodeInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      excludedDatanodeInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.westboy.namenode.rpc.ChooseDataNodeRequest)
  }

  // @@protoc_insertion_point(class_scope:com.westboy.namenode.rpc.ChooseDataNodeRequest)
  private static final com.westboy.namenode.rpc.model.ChooseDataNodeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.westboy.namenode.rpc.model.ChooseDataNodeRequest();
  }

  public static com.westboy.namenode.rpc.model.ChooseDataNodeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChooseDataNodeRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChooseDataNodeRequest>() {
    @java.lang.Override
    public ChooseDataNodeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChooseDataNodeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChooseDataNodeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChooseDataNodeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.westboy.namenode.rpc.model.ChooseDataNodeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

