// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

public interface ChooseDataNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.westboy.namenode.rpc.ChooseDataNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string excludedDatanodeInfo = 2;</code>
   * @return The excludedDatanodeInfo.
   */
  java.lang.String getExcludedDatanodeInfo();
  /**
   * <code>string excludedDatanodeInfo = 2;</code>
   * @return The bytes for excludedDatanodeInfo.
   */
  com.google.protobuf.ByteString
      getExcludedDatanodeInfoBytes();
}
