// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

public interface ChooseDataNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.westboy.namenode.rpc.ChooseDataNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string datanodeInfo = 2;</code>
   * @return The datanodeInfo.
   */
  java.lang.String getDatanodeInfo();
  /**
   * <code>string datanodeInfo = 2;</code>
   * @return The bytes for datanodeInfo.
   */
  com.google.protobuf.ByteString
      getDatanodeInfoBytes();
}
