// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

public interface FetchEditlogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.westboy.namenode.rpc.FetchEditlogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 syncTxid = 2;</code>
   * @return The syncTxid.
   */
  long getSyncTxid();
}
