// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_FetchEditlogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_FetchEditlogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_FetchEditlogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_FetchEditlogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_CreateFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_AllocateDataNodesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_AllocateDataNodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ReallocateDataNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ReallocateDataNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ReportStorageInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ReportStorageInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ReportStorageInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ReportStorageInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ReportFileInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ReportFileInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ReportFileInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ReportFileInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_ChooseDataNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_ChooseDataNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_RebalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_RebalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_westboy_namenode_rpc_RebalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_westboy_namenode_rpc_RebalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022\030com.westboy.na" +
      "menode.rpc\"\'\n\017RegisterRequest\022\024\n\014datanod" +
      "eInfo\030\001 \001(\t\"\"\n\020RegisterResponse\022\016\n\006statu" +
      "s\030\001 \001(\005\"(\n\020HeartbeatRequest\022\024\n\014datanodeI" +
      "nfo\030\001 \001(\t\"5\n\021HeartbeatResponse\022\016\n\006status" +
      "\030\001 \001(\005\022\020\n\010commands\030\002 \001(\t\"\034\n\014MkdirRequest" +
      "\022\014\n\004path\030\001 \001(\t\"\037\n\rMkdirResponse\022\016\n\006statu" +
      "s\030\001 \001(\005\"\037\n\017ShutdownRequest\022\014\n\004code\030\001 \001(\005" +
      "\"\"\n\020ShutdownResponse\022\016\n\006status\030\001 \001(\005\"\'\n\023" +
      "FetchEditlogRequest\022\020\n\010syncTxid\030\002 \001(\003\"8\n" +
      "\024FetchEditlogResponse\022\016\n\006status\030\001 \001(\005\022\020\n" +
      "\010editsLog\030\002 \001(\t\"+\n\033UpdateCheckpointTxidR" +
      "equest\022\014\n\004txid\030\001 \001(\003\".\n\034UpdateCheckpoint" +
      "TxidResponse\022\016\n\006status\030\001 \001(\005\"%\n\021CreateFi" +
      "leRequest\022\020\n\010filename\030\001 \001(\t\"$\n\022CreateFil" +
      "eResponse\022\016\n\006status\030\001 \001(\005\",\n\030AllocateDat" +
      "aNodesRequest\022\020\n\010fileInfo\030\001 \001(\t\"A\n\031Alloc" +
      "ateDataNodesResponse\022\016\n\006status\030\001 \001(\005\022\024\n\014" +
      "datanodeInfo\030\002 \001(\t\"K\n\031ReallocateDataNode" +
      "Request\022\020\n\010fileInfo\030\001 \001(\t\022\034\n\024excludedDat" +
      "anodeInfo\030\002 \001(\t\"B\n\032ReallocateDataNodeRes" +
      "ponse\022\016\n\006status\030\001 \001(\005\022\024\n\014datanodeInfo\030\002 " +
      "\001(\t\"E\n\030ReportStorageInfoRequest\022\024\n\014datan" +
      "odeInfo\030\001 \001(\t\022\023\n\013storageInfo\030\002 \001(\t\"+\n\031Re" +
      "portStorageInfoResponse\022\016\n\006status\030\001 \001(\005\"" +
      "?\n\025ReportFileInfoRequest\022\024\n\014datanodeInfo" +
      "\030\001 \001(\t\022\020\n\010fileInfo\030\004 \001(\t\"(\n\026ReportFileIn" +
      "foResponse\022\016\n\006status\030\001 \001(\005\"G\n\025ChooseData" +
      "NodeRequest\022\020\n\010filename\030\001 \001(\t\022\034\n\024exclude" +
      "dDatanodeInfo\030\002 \001(\t\">\n\026ChooseDataNodeRes" +
      "ponse\022\016\n\006status\030\001 \001(\005\022\024\n\014datanodeInfo\030\002 " +
      "\001(\t\"\022\n\020RebalanceRequest\"#\n\021RebalanceResp" +
      "onse\022\016\n\006status\030\001 \001(\005B4\n\036com.westboy.name" +
      "node.rpc.modelB\020NameNodeRpcModelP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_westboy_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_westboy_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_RegisterRequest_descriptor,
        new java.lang.String[] { "DatanodeInfo", });
    internal_static_com_westboy_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_westboy_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_westboy_namenode_rpc_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_westboy_namenode_rpc_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_HeartbeatRequest_descriptor,
        new java.lang.String[] { "DatanodeInfo", });
    internal_static_com_westboy_namenode_rpc_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_westboy_namenode_rpc_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", "Commands", });
    internal_static_com_westboy_namenode_rpc_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_westboy_namenode_rpc_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_MkdirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_com_westboy_namenode_rpc_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_westboy_namenode_rpc_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_MkdirResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_westboy_namenode_rpc_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_westboy_namenode_rpc_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ShutdownRequest_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_westboy_namenode_rpc_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_westboy_namenode_rpc_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ShutdownResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_westboy_namenode_rpc_FetchEditlogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_westboy_namenode_rpc_FetchEditlogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_FetchEditlogRequest_descriptor,
        new java.lang.String[] { "SyncTxid", });
    internal_static_com_westboy_namenode_rpc_FetchEditlogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_westboy_namenode_rpc_FetchEditlogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_FetchEditlogResponse_descriptor,
        new java.lang.String[] { "Status", "EditsLog", });
    internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidRequest_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_UpdateCheckpointTxidResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_westboy_namenode_rpc_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_westboy_namenode_rpc_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_CreateFileRequest_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_com_westboy_namenode_rpc_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_westboy_namenode_rpc_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_CreateFileResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_westboy_namenode_rpc_AllocateDataNodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_westboy_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_AllocateDataNodesRequest_descriptor,
        new java.lang.String[] { "FileInfo", });
    internal_static_com_westboy_namenode_rpc_AllocateDataNodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_westboy_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_AllocateDataNodesResponse_descriptor,
        new java.lang.String[] { "Status", "DatanodeInfo", });
    internal_static_com_westboy_namenode_rpc_ReallocateDataNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_westboy_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ReallocateDataNodeRequest_descriptor,
        new java.lang.String[] { "FileInfo", "ExcludedDatanodeInfo", });
    internal_static_com_westboy_namenode_rpc_ReallocateDataNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_westboy_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ReallocateDataNodeResponse_descriptor,
        new java.lang.String[] { "Status", "DatanodeInfo", });
    internal_static_com_westboy_namenode_rpc_ReportStorageInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_westboy_namenode_rpc_ReportStorageInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ReportStorageInfoRequest_descriptor,
        new java.lang.String[] { "DatanodeInfo", "StorageInfo", });
    internal_static_com_westboy_namenode_rpc_ReportStorageInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_westboy_namenode_rpc_ReportStorageInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ReportStorageInfoResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_westboy_namenode_rpc_ReportFileInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_westboy_namenode_rpc_ReportFileInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ReportFileInfoRequest_descriptor,
        new java.lang.String[] { "DatanodeInfo", "FileInfo", });
    internal_static_com_westboy_namenode_rpc_ReportFileInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_westboy_namenode_rpc_ReportFileInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ReportFileInfoResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ChooseDataNodeRequest_descriptor,
        new java.lang.String[] { "Filename", "ExcludedDatanodeInfo", });
    internal_static_com_westboy_namenode_rpc_ChooseDataNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_westboy_namenode_rpc_ChooseDataNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_ChooseDataNodeResponse_descriptor,
        new java.lang.String[] { "Status", "DatanodeInfo", });
    internal_static_com_westboy_namenode_rpc_RebalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_westboy_namenode_rpc_RebalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_RebalanceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_westboy_namenode_rpc_RebalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_westboy_namenode_rpc_RebalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_westboy_namenode_rpc_RebalanceResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
