// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

public interface ReallocateDataNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.westboy.namenode.rpc.ReallocateDataNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileInfo = 1;</code>
   * @return The fileInfo.
   */
  java.lang.String getFileInfo();
  /**
   * <code>string fileInfo = 1;</code>
   * @return The bytes for fileInfo.
   */
  com.google.protobuf.ByteString
      getFileInfoBytes();

  /**
   * <code>string excludedDatanodeInfo = 2;</code>
   * @return The excludedDatanodeInfo.
   */
  java.lang.String getExcludedDatanodeInfo();
  /**
   * <code>string excludedDatanodeInfo = 2;</code>
   * @return The bytes for excludedDatanodeInfo.
   */
  com.google.protobuf.ByteString
      getExcludedDatanodeInfoBytes();
}
