// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.westboy.namenode.rpc.model;

public interface ReportStorageInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.westboy.namenode.rpc.ReportStorageInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datanodeInfo = 1;</code>
   * @return The datanodeInfo.
   */
  java.lang.String getDatanodeInfo();
  /**
   * <code>string datanodeInfo = 1;</code>
   * @return The bytes for datanodeInfo.
   */
  com.google.protobuf.ByteString
      getDatanodeInfoBytes();

  /**
   * <code>string storageInfo = 2;</code>
   * @return The storageInfo.
   */
  java.lang.String getStorageInfo();
  /**
   * <code>string storageInfo = 2;</code>
   * @return The bytes for storageInfo.
   */
  com.google.protobuf.ByteString
      getStorageInfoBytes();
}
